# © 2024 by Steven Johann Koch. All rights reserved.
#
# This software is confidential. It is provided for evaluation only. No part of this software,
# including but not limited to code, design, and documentation, may be used, modified, distributed,
# or otherwise exploited without explicit written consent from Steven Johann Koch.
#
# This file is part of the Causal project and is subject to copyright and intellectual property laws.
# Any modification, redistribution, or use of this file is prohibited without explicit permission
# from the author, Steven Johann Koch.
#
# Please contact steven@causal.site or steven.johann.koch@googlemail.com for any inquiries or permissions.

AWSTemplateFormatVersion: "2010-09-09"
Description: "Causal Infrastructure Setup"

Parameters:

  LogBucketExpirationInDays:
    Type: Number
    Default: 90

  # Default

  Environment:
    Type: String
    Default: "const"
  Reference:
    Type: String
    Default: "aws"

Resources:
  
  # Buckets

  CausalBucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub "csl-${Environment}-bucket"
      AccessControl: Private

  CausalLogBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub 'csl-logs-${AWS::Region}-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: "ExpireOldLogs"
            Status: "Enabled"
            ExpirationInDays: !Ref LogBucketExpirationInDays

  CausalArtifactBucket: # TODO: Bucket Policy
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub 'csl-artifacts-${AWS::Region}-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled

  # Security

  CausalKeyGeneral:
    Type: "AWS::KMS::Key"
    DeletionPolicy: Retain
    Properties:
      Description: "General KMS key"
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: "Enable IAM User Permissions"
            Effect: "Allow"
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"
      Enabled: true
      EnableKeyRotation: true

  CausalKeyGeneralAlias:
    Type: "AWS::KMS::Alias"
    DeletionPolicy: Retain
    Properties:
      AliasName: !Sub "alias/csl-${Environment}-key"
      TargetKeyId: !Ref CausalKeyGeneral

  # IAM

  CausalRoleAdmin:
    Type: 'AWS::IAM::Role'
    DeletionPolicy: Retain
    Properties:
      RoleName: 'CausalAdminRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [ 'ec2.amazonaws.com', 'lambda.amazonaws.com' ]
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: 'AdminAccess'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'